"""credit client, canal cash/momo, cloture scindee, edition employe

Revision ID: 148cef549c3b
Revises: 4d6acffb9d03
Create Date: 2026-09-22 05:33:19.608804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '148cef549c3b'
down_revision: Union[str, None] = '4d6acffb9d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate ne gère pas deux particularités Postgres, ajoutées ici :
    #  1. la valeur 'credit_repayment' sur le type enum EXISTANT moneymovementtype
    #     (ALTER TYPE ... ADD VALUE, dispo en transaction depuis PG 12),
    #  2. la création explicite du type enum moneymovementchannel — op.add_column
    #     ne déclenche pas le CreateType de SQLAlchemy (contrairement à create_table).
    op.execute("ALTER TYPE moneymovementtype ADD VALUE IF NOT EXISTS 'credit_repayment'")
    op.execute("CREATE TYPE moneymovementchannel AS ENUM ('cash', 'mobile_money')")

    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_uuid', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_business_id'), 'customer', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_client_uuid'), 'customer', ['client_uuid'], unique=True)
    op.add_column('dailyclosing', sa.Column('expected_momo', sa.Integer(), nullable=True))
    op.add_column('dailyclosing', sa.Column('actual_momo', sa.Integer(), nullable=True))
    op.add_column('dailyclosing', sa.Column('difference_momo', sa.Integer(), nullable=True))
    op.add_column('moneymovement', sa.Column('channel', sa.Enum('cash', 'mobile_money', name='moneymovementchannel', create_type=False), nullable=True))
    op.add_column('moneymovement', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'moneymovement', 'customer', ['customer_id'], ['id'])
    op.add_column('sale', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'sale', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'customer_id')
    op.drop_constraint(None, 'moneymovement', type_='foreignkey')
    op.drop_column('moneymovement', 'customer_id')
    op.drop_column('moneymovement', 'channel')
    op.execute("DROP TYPE moneymovementchannel")
    op.drop_column('dailyclosing', 'difference_momo')
    op.drop_column('dailyclosing', 'actual_momo')
    op.drop_column('dailyclosing', 'expected_momo')
    op.drop_index(op.f('ix_customer_client_uuid'), table_name='customer')
    op.drop_index(op.f('ix_customer_business_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
