"""telemetrie plateforme shifts parametres entreprise

Revision ID: 47184169e6ce
Revises: b614d779857a
Create Date: 2026-09-24 04:54:13.066468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47184169e6ce'
down_revision: Union[str, None] = 'b614d779857a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platformevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platformevent_business_id'), 'platformevent', ['business_id'], unique=False)
    op.create_index(op.f('ix_platformevent_created_at'), 'platformevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_platformevent_type'), 'platformevent', ['type'], unique=False)
    op.create_table('adminauditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['superadminuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminauditlog_admin_id'), 'adminauditlog', ['admin_id'], unique=False)
    op.create_index(op.f('ix_adminauditlog_created_at'), 'adminauditlog', ['created_at'], unique=False)
    op.create_table('adminnote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['superadminuser.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminnote_business_id'), 'adminnote', ['business_id'], unique=False)
    op.create_table('supportticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='ticketstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['superadminuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supportticket_business_id'), 'supportticket', ['business_id'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_ok', sa.Boolean(), nullable=True),
    sa.Column('last_sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pending_ops', sa.Integer(), nullable=False),
    sa.Column('rejected_ops', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'device_key', name='uq_device_business_key')
    )
    op.create_index(op.f('ix_device_business_id'), 'device', ['business_id'], unique=False)
    op.create_index(op.f('ix_device_device_key'), 'device', ['device_key'], unique=False)
    op.create_table('shift',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_uuid', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('opening_cash', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('counted_cash', sa.Integer(), nullable=True),
    sa.Column('expected_cash', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_business_id'), 'shift', ['business_id'], unique=False)
    op.create_index(op.f('ix_shift_client_uuid'), 'shift', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_shift_user_id'), 'shift', ['user_id'], unique=False)
    op.add_column('business', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business', sa.Column('logo_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('moneymovement', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moneymovement', 'category')
    op.drop_column('business', 'is_suspended')
    op.drop_column('business', 'logo_data')
    op.drop_column('business', 'email')
    op.drop_column('business', 'phone')
    op.drop_column('business', 'address')
    op.drop_index(op.f('ix_shift_user_id'), table_name='shift')
    op.drop_index(op.f('ix_shift_client_uuid'), table_name='shift')
    op.drop_index(op.f('ix_shift_business_id'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('ix_device_device_key'), table_name='device')
    op.drop_index(op.f('ix_device_business_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_supportticket_business_id'), table_name='supportticket')
    op.drop_table('supportticket')
    op.drop_index(op.f('ix_adminnote_business_id'), table_name='adminnote')
    op.drop_table('adminnote')
    op.drop_index(op.f('ix_adminauditlog_created_at'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_admin_id'), table_name='adminauditlog')
    op.drop_table('adminauditlog')
    op.drop_index(op.f('ix_platformevent_type'), table_name='platformevent')
    op.drop_index(op.f('ix_platformevent_created_at'), table_name='platformevent')
    op.drop_index(op.f('ix_platformevent_business_id'), table_name='platformevent')
    op.drop_table('platformevent')
    # ### end Alembic commands ###
