"""produit code-barres categorie stockable

Revision ID: 5eb97856a1ad
Revises: 47184169e6ce
Create Date: 2026-09-24 05:12:07.167888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5eb97856a1ad'
down_revision: Union[str, None] = '47184169e6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('is_stockable', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_column('product', 'is_stockable')
    op.drop_column('product', 'category')
    op.drop_column('product', 'barcode')
    # ### end Alembic commands ###
