"""anomaly resolution

Revision ID: b614d779857a
Revises: 47f3ad9c2ff7
Create Date: 2026-09-24 04:48:43.420830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b614d779857a'
down_revision: Union[str, None] = '47f3ad9c2ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalyresolution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('anomaly_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'anomaly_type', 'source_id', name='uq_anomaly_resolution')
    )
    op.create_index(op.f('ix_anomalyresolution_business_id'), 'anomalyresolution', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalyresolution_business_id'), table_name='anomalyresolution')
    op.drop_table('anomalyresolution')
    # ### end Alembic commands ###
